import { getPool } from './connection.js';

const schemaSql = `
IF OBJECT_ID('dbo.BOOKEDROOMMATES', 'U') IS NOT NULL DROP TABLE dbo.BOOKEDROOMMATES;
IF OBJECT_ID('dbo.BOOKEDMAIDS', 'U') IS NOT NULL DROP TABLE dbo.BOOKEDMAIDS;
IF OBJECT_ID('dbo.BOOKEDTUITIONS', 'U') IS NOT NULL DROP TABLE dbo.BOOKEDTUITIONS;
IF OBJECT_ID('dbo.APPLIEDROOMMATES', 'U') IS NOT NULL DROP TABLE dbo.APPLIEDROOMMATES;
IF OBJECT_ID('dbo.APPLIEDMAIDS', 'U') IS NOT NULL DROP TABLE dbo.APPLIEDMAIDS;
IF OBJECT_ID('dbo.APPLIEDTUITIONS', 'U') IS NOT NULL DROP TABLE dbo.APPLIEDTUITIONS;
IF OBJECT_ID('dbo.HOUSECONTACTS', 'U') IS NOT NULL DROP TABLE dbo.HOUSECONTACTS;
IF OBJECT_ID('dbo.MARKETPLACELISTINGS', 'U') IS NOT NULL DROP TABLE dbo.MARKETPLACELISTINGS;
IF OBJECT_ID('dbo.HOUSERENTLISTINGS', 'U') IS NOT NULL DROP TABLE dbo.HOUSERENTLISTINGS;
IF OBJECT_ID('dbo.ROOMMATELISTINGS', 'U') IS NOT NULL DROP TABLE dbo.ROOMMATELISTINGS;
IF OBJECT_ID('dbo.MAIDS', 'U') IS NOT NULL DROP TABLE dbo.MAIDS;
IF OBJECT_ID('dbo.TUITIONS', 'U') IS NOT NULL DROP TABLE dbo.TUITIONS;
IF OBJECT_ID('dbo.USERACTIVITIES', 'U') IS NOT NULL DROP TABLE dbo.USERACTIVITIES;
IF OBJECT_ID('dbo.SUBSCRIPTIONPAYMENTS', 'U') IS NOT NULL DROP TABLE dbo.SUBSCRIPTIONPAYMENTS;
IF OBJECT_ID('dbo.ANNOUNCEMENTS', 'U') IS NOT NULL DROP TABLE dbo.ANNOUNCEMENTS;
IF OBJECT_ID('dbo.USERS', 'U') IS NOT NULL DROP TABLE dbo.USERS;

CREATE TABLE dbo.USERS (
  user_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(120) NOT NULL,
  email NVARCHAR(180) NOT NULL UNIQUE,
  password_hash NVARCHAR(255) NOT NULL,
  role NVARCHAR(20) NOT NULL CHECK (role IN ('student', 'admin')),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.ANNOUNCEMENTS (
  announcement_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  title NVARCHAR(200) NOT NULL,
  message NVARCHAR(MAX) NOT NULL,
  created_by UNIQUEIDENTIFIER NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_ANNOUNCEMENTS_USERS FOREIGN KEY (created_by) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.SUBSCRIPTIONPAYMENTS (
  payment_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  status NVARCHAR(30) NOT NULL,
  payment_date DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_SUBSCRIPTIONPAYMENTS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.USERACTIVITIES (
  activity_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  action_type NVARCHAR(80) NOT NULL,
  reference_table NVARCHAR(60) NOT NULL,
  reference_id UNIQUEIDENTIFIER NULL,
  [timestamp] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_USERACTIVITIES_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.TUITIONS (
  tuition_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  subject NVARCHAR(140) NOT NULL,
  salary DECIMAL(10, 2) NOT NULL,
  location NVARCHAR(160) NOT NULL,
  status NVARCHAR(30) NOT NULL DEFAULT 'open',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_TUITIONS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.APPLIEDTUITIONS (
  application_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  tuition_id UNIQUEIDENTIFIER NOT NULL,
  user_id UNIQUEIDENTIFIER NOT NULL,
  status NVARCHAR(30) NOT NULL DEFAULT 'pending',
  applied_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_APPLIEDTUITIONS_TUITIONS FOREIGN KEY (tuition_id) REFERENCES dbo.TUITIONS(tuition_id),
  CONSTRAINT FK_APPLIEDTUITIONS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.BOOKEDTUITIONS (
  booking_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  application_id UNIQUEIDENTIFIER NOT NULL UNIQUE,
  confirmed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_BOOKEDTUITIONS_APPLIEDTUITIONS FOREIGN KEY (application_id) REFERENCES dbo.APPLIEDTUITIONS(application_id)
);

CREATE TABLE dbo.MAIDS (
  maid_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  salary DECIMAL(10, 2) NOT NULL,
  location NVARCHAR(160) NOT NULL,
  availability NVARCHAR(40) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_MAIDS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.APPLIEDMAIDS (
  application_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  maid_id UNIQUEIDENTIFIER NOT NULL,
  user_id UNIQUEIDENTIFIER NOT NULL,
  status NVARCHAR(30) NOT NULL DEFAULT 'pending',
  applied_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_APPLIEDMAIDS_MAIDS FOREIGN KEY (maid_id) REFERENCES dbo.MAIDS(maid_id),
  CONSTRAINT FK_APPLIEDMAIDS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.BOOKEDMAIDS (
  booking_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  application_id UNIQUEIDENTIFIER NOT NULL UNIQUE,
  confirmed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_BOOKEDMAIDS_APPLIEDMAIDS FOREIGN KEY (application_id) REFERENCES dbo.APPLIEDMAIDS(application_id)
);

CREATE TABLE dbo.ROOMMATELISTINGS (
  listing_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  location NVARCHAR(160) NOT NULL,
  rent DECIMAL(10, 2) NOT NULL,
  preference NVARCHAR(MAX) NULL,
  [type] NVARCHAR(20) NOT NULL CHECK ([type] IN ('host', 'seeker')),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_ROOMMATELISTINGS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.APPLIEDROOMMATES (
  application_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  listing_id UNIQUEIDENTIFIER NOT NULL,
  user_id UNIQUEIDENTIFIER NOT NULL,
  status NVARCHAR(30) NOT NULL DEFAULT 'pending',
  applied_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_APPLIEDROOMMATES_ROOMMATELISTINGS FOREIGN KEY (listing_id) REFERENCES dbo.ROOMMATELISTINGS(listing_id),
  CONSTRAINT FK_APPLIEDROOMMATES_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.BOOKEDROOMMATES (
  booking_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  application_id UNIQUEIDENTIFIER NOT NULL UNIQUE,
  confirmed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_BOOKEDROOMMATES_APPLIEDROOMMATES FOREIGN KEY (application_id) REFERENCES dbo.APPLIEDROOMMATES(application_id)
);

CREATE TABLE dbo.HOUSERENTLISTINGS (
  house_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  location NVARCHAR(160) NOT NULL,
  rent DECIMAL(10, 2) NOT NULL,
  rooms INT NOT NULL,
  description NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_HOUSERENTLISTINGS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.HOUSECONTACTS (
  contact_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  house_id UNIQUEIDENTIFIER NOT NULL,
  user_id UNIQUEIDENTIFIER NOT NULL,
  message NVARCHAR(MAX) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_HOUSECONTACTS_HOUSERENTLISTINGS FOREIGN KEY (house_id) REFERENCES dbo.HOUSERENTLISTINGS(house_id),
  CONSTRAINT FK_HOUSECONTACTS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);

CREATE TABLE dbo.MARKETPLACELISTINGS (
  item_id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  user_id UNIQUEIDENTIFIER NOT NULL,
  title NVARCHAR(160) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  [condition] NVARCHAR(40) NOT NULL,
  status NVARCHAR(30) NOT NULL DEFAULT 'available',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_MARKETPLACELISTINGS_USERS FOREIGN KEY (user_id) REFERENCES dbo.USERS(user_id)
);
`;

let schemaReady = false;

export async function ensureSchema() {
  if (schemaReady) {
    return;
  }
  const pool = await getPool();

  const result = await pool
    .request()
    .query("SELECT OBJECT_ID('dbo.USERS', 'U') AS users_table_id");

  if (!result.recordset[0].users_table_id) {
    await pool.request().query(schemaSql);

    // Seed a default admin account for first boot.
    await pool.request().query(`
      INSERT INTO dbo.USERS (name, email, password_hash, role)
      VALUES ('System Admin', 'admin@bachelore.local', '$2a$10$m42Hi9dSi8NQ5ec7QcHBOecVaHPfKja4h74QE8XABdUB7jzQx8jYu', 'admin')
    `);
  }

  schemaReady = true;
}
